### ISSUE TITLE
Add `get_class_by_hash` to Sequencer provider

### ISSUE THREAD

**Issue by ivpavici** [0xs34n/starknet.js#361]
https://github.com/starkware-libs/cairo-lang/blob/54d7e92a703b3b5a1e07e9389608178129946efc/src/starkware/starknet/services/api/feeder_gateway/feeder_gateway_client.py#L199

**Comment by penovicp** [comment]
I'll look into this.

**Comment by dhruvkelawala** [comment]
We also need this feature as a priority. Turns out we already have it in the api https://github.com/0xs34n/starknet.js/blob/f168beba86d2a5122b8d3fb5728574f0510b9394/src/types/api/sequencer.ts#L337 . Just need to implement it.

@penovicp If you are busy with something, let me know, I can work on this
