### ISSUE TITLE
Determine feasibility of pure ESM package

### ISSUE THREAD

**Issue by paulmillr** [0xs34n/starknet.js#545]
What are your thoughts on that? Can common.js be dropped?

1. All stable node.js versions support ESM
2. Same with browsers https://caniuse.com/?search=ESM
3. Using ESM removes necessity of building / bundling files

Sindre Sorhus who maintains tons of popular packages have been using esm for a long time. His guide: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

I want to move to ESM asap. Note that esm deps can't be used from commonjs, BUT commonjs deps can be used from ESM.

**Comment by janek26** [comment]
> Note that esm deps can't be used from commonjs
I guess this a big problem for us

**Comment by dhruvkelawala** [comment]
Yes

**Comment by paulmillr** [comment]
Could you clarify why? Every env supports esm these days except for electron where folks use bundlers to convert back to commonjs.

**Comment by janek26** [comment]
@paulmillr what's the drawback of supporting cjs on your end?

I'm pretty sure we have plenty of applications which use starknet.js as a dependency and still use cjs

**Comment by dhruvkelawala** [comment]
I agree on same

**Comment by ivpavici** [comment]
I would just like to add that this topic would maybe be better suited in 1-2 months - since now we have a very important Starknet update coming in ~2 weeks and we need to adapt starknet.js accordingly!

**Comment by 0xs34n** [comment]
Hey Paul, I agree that pure ESM is the direction that JS packages should move going forward.

However, as you know, we're all working around the clock to migrate and support starknet v0.11. Would it be possible to support cjs so that starknet.js can support starknet v0.11, and then we can discuss moving to pure ESM for subsequent versions of noble after starknet v0.11?

I think our top priority is supporting starknet v0.11 as fast and best we can. Then we can move to pure ESM when things are more settled.

Let me know if that would work for you

**Comment by paulmillr** [comment]
That makes sense. How about I release 0.8.1 with esm+commonjs, for your release? Any bugfixes we could do 0.8.x And 1.0.0 pure esm after this.

**Comment by ivpavici** [comment]
this sounds like a nice compromise :)

**Comment by paulmillr** [comment]
OK folks, cjs is done: use https://github.com/paulmillr/micro-starknet 0.2.1; api is the same. I've moved stark curve back into a separate package because it seems like stark would be changing more than other curves.
