### ISSUE TITLE
`bigint` doesn't have all the methods BN.js has (`umod`, `toArray`) 

### ISSUE THREAD

**Issue by ivpavici** [0xs34n/starknet.js#564]
**Is your feature request related to a problem? Please describe.**

`bigint` doesn't have all the methods BN.js has (`umod`, `toArray`) 

**Describe the solution you'd like**

We can implement the required BN.js methods
- `toArrray` can be solved with `num.hexToBytes` ?

**Describe alternatives you've considered**

Ask the projects to handle it themselves

**Comment by janek26** [comment]
toArray is indeed better handled by noble/hashes or something, it’s just casting to Uint8Array

umod is as simple as:
```typescript

function umod(dividend: bigint, divisor: bigint): bigint {
  if (divisor <= 0n) {
    throw new Error("Divisor must be a positive integer.");
  }

  const remainder = dividend % divisor;
  return remainder >= 0n ? remainder : remainder + divisor;
}

// Example usage:
const dividend = -10n;
const divisor = 7n;
console.log(umod(dividend, divisor)); // Output: 4n
```

**Comment by penovicp** [comment]
My gut reaction is to favour letting whoever needs something not used by the library itself handle it themselves. On the other hand if the feature request is not going to grow beyond `umod` I don't mind it being added since it's fairly trivial as Janek has demonstrated.

A potential future change that somewhat relates to the reported issue might be to allow some of the interfaces and types to accept generics, e.g. `ProviderInterface<T = bigint>` so end users could do something roughly like `const provider: ProviderInterface<BN> = transform(starknet.defaultProvider)` where the transformation wraps all the provider methods with something like `(...params) => parseWithNumberCast(stringify(method(...params)), (x) => castNumberToBN(x)))` so an arbitrary big number class could be used. But then again, I don't think it makes sense to squeeze it into v5 and I'm not sure it would see much use after.

**Comment by tabaktoni** [comment]
Update docs with explanation, this example, and reference to 3rd. party packages

**Comment by ivpavici** [comment]
Now I realized (again) that @PhilippeR26 covered these examples in https://github.com/0xs34n/starknet.js/pull/636 , so I think this is fine as it is.

Also, there are libraries with more complex utilities which users can find and integrate in their apps, for example: 
https://github.com/juanelas/bigint-mod-arith
