### ISSUE TITLE
Failed to create a contract object by obtaining the ABI through the API.

### ISSUE THREAD

**Issue by infra403** [0xs34n/starknet.js#648]
**Describe the bug**
Failed to create a contract object by obtaining the ABI through the API.

**To Reproduce**
Steps to reproduce the behavior
`export const claim = async (address, privateKey) => {
  const starkKeyPair = ec.getKeyPair(privateKey);
  const starkKeyPub = ec.getStarkKey(starkKeyPair);
  const account = new Account(provider, address, starkKeyPair);

  // initialize contract using abi, address and provider
  const contractAddress = "0x00630eb5544172af8716956ff6b8f382b17b8d67f11bf1d8e9e7c8e10e31a2ac"
  const contractClassHash = "0x03bc24c464f6904a8a678ae03ca4d922dd4879392a438078989ad203157d957f"

  const contractClass = await provider.getClassAt(contractAddress);
  if (contractClass.abi === undefined) { throw new Error("no abi.") };

  const contract = new Contract(contractClass.abi, contractAddress, account)
  // make contract call
  const result = await contract.airdrop_amount(address)
  console.log("claim", address, result)
  return result
}
`
**Expected behavior**
The contract can be called normally after obtaining the ABI.
**Screenshots**

TypeError: Cannot read properties of undefined (reading 'length')

**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker]
- Node version [19.8.1"]
- "starknet": "^4.22.0"
- Network [mainnet-alpha]

**Additional context**

**Comment by ivpavici** [comment]
Hello!
I guess your issue is because you call this [contract ](https://starkscan.co/contract/0x00630eb5544172af8716956ff6b8f382b17b8d67f11bf1d8e9e7c8e10e31a2ac) which is a Cairo 1 contract, but starknet JS 4.22.0 doesn't support Cairo 1 contracts.

Please try with v5 : `npm install starknet@next`
And check the guides for changes in v5: https://www.starknetjs.com/docs/next/guides/migrate
